### ISSUE TITLE
How use pstress to test Percona XtraDB Cluster deployed using Percona Operator

### ISSUE THREAD

**Issue by imriss** [Percona-QA/pstress#8]
I would to test a Percona XtraDB Cluster deployed using Percona Operator. I cannot install pstress inside the pxc pods. And, when trying to install it in a separate pod, I get this error:
```
CMake Error at cmake/PQFindMySQLFork.cmake:111 (MESSAGE):
  * Could NOT find Percona Server library
```

Please let me know if there is a documentation on how to this such a test.
Thanks

**Comment by mohitj1988** [comment]
Hello,
Could you please share the cmake command used for compiling pxc?
As per docs,
cmake . -DBASEDIR=/path/to/pxc/bld/directory -DPERCONACLUSTER=ON

**Comment by imriss** [comment]
Hello, Thanks for the reply. 
I cannot install cmake inside the pxc pod (which is deployed using Percona Operator). It asks for the root password when trying `su`.

**Comment by mohitj1988** [comment]
Hello,

PXC in kubernetes is running inside it's base docker image with the corresponding restrictions - no extra packages by default, free space limitations etc.
Usually all interactions with DB are made via network inside the kubernetes by sending traffic to something like 'my-cluster.my-cluster.my-cluster-namespace.svc.cluster.local' (internal DNS record).
So in majority of cases we recommend to run tests remotely since the DB inside kubernetes could face at least two bottlenecks - network bandwidh between cluster member, CPU/RAM/IOps limitation - all caused by the platform.

Secondly, compiling pstress using rpm packages is not straight-forward. The recommended way would be to either use PXC binary tarball build package OR make your own build manually and use the build directory to compile pstress.

Make sure it is not from the same container/pod
